import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

export const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr" className="h-full">
			<body
				className={`${poppins.className} antialiased flex min-h-full flex-col`}
			>
				<Navbar />
				<main className="flex justify-center bg-secondary pt-32 max-md:pt-[90px] h-[calc(100vh-8rem)] grow">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
